import type { MailSimple } from "./types";

const seed: MailSimple[] = [
  {
    id: "m-001",
    sender: "Alice Chen",
    senderInitial: "A",
    senderColor: "bg-rose-500",
    subject: "Project update for Q2",
    preview:
      "Hi! Quick update on the Q2 roadmap. We've reshuffled the milestones and I'd love your take before Friday.",
    timeLabel: "3 min",
    unread: true,
    hasAttachment: true,
    starred: false,
  },
  {
    id: "m-002",
    sender: "Ben Karim",
    senderInitial: "B",
    senderColor: "bg-amber-500",
    subject: "Lunch tomorrow?",
    preview:
      "Are you free around 12:30? There's a new ramen place near the office I want to try.",
    timeLabel: "1 h",
    unread: true,
    hasAttachment: false,
    starred: false,
  },
  {
    id: "m-003",
    sender: "Carol Park",
    senderInitial: "C",
    senderColor: "bg-teal-500",
    subject: "Receipts for May",
    preview:
      "Forwarding the receipts for May. Let me know if any of them need to be re-categorized.",
    timeLabel: "2 h",
    unread: false,
    hasAttachment: true,
    starred: false,
  },
  {
    id: "m-004",
    sender: "Daniel Lim",
    senderInitial: "D",
    senderColor: "bg-indigo-500",
    subject: "Re: launch checklist",
    preview:
      "Looks great. Two small things on the rollback step — replying inline below.",
    timeLabel: "4 h",
    unread: false,
    hasAttachment: false,
    starred: true,
  },
  {
    id: "m-005",
    sender: "Elena Rossi",
    senderInitial: "E",
    senderColor: "bg-pink-500",
    subject: "Welcome to the team",
    preview:
      "So glad to have you with us! Here are a few onboarding docs and the calendar invite for Monday.",
    timeLabel: "Yesterday",
    unread: false,
    hasAttachment: false,
    starred: false,
  },
  {
    id: "m-006",
    sender: "Frank Wu",
    senderInitial: "F",
    senderColor: "bg-emerald-500",
    subject: "Quarterly figures",
    preview:
      "Attaching the figures for Q1. Numbers look strong on engagement but conversion is flat.",
    timeLabel: "Yesterday",
    unread: false,
    hasAttachment: true,
    starred: false,
  },
  {
    id: "m-007",
    sender: "Grace Müller",
    senderInitial: "G",
    senderColor: "bg-sky-500",
    subject: "Out of office: 5/24 – 5/31",
    preview:
      "I'll be out next week — please reach out to Jack for anything urgent during that window.",
    timeLabel: "Mon",
    unread: true,
    hasAttachment: false,
    starred: false,
  },
  {
    id: "m-008",
    sender: "Henry Tan",
    senderInitial: "H",
    senderColor: "bg-violet-500",
    subject: "Notion workspace invite",
    preview:
      "You've been invited to the Product workspace. Click the link to accept — no signup required.",
    timeLabel: "Mon",
    unread: false,
    hasAttachment: false,
    starred: false,
  },
  {
    id: "m-009",
    sender: "Iris Park",
    senderInitial: "I",
    senderColor: "bg-orange-500",
    subject: "Re: design review feedback",
    preview:
      "Appreciate the detailed notes. I'll fold the spacing fixes into the next Figma pass tonight.",
    timeLabel: "Sun",
    unread: false,
    hasAttachment: false,
    starred: false,
  },
  {
    id: "m-010",
    sender: "Jack Doh",
    senderInitial: "J",
    senderColor: "bg-cyan-500",
    subject: "Action items from sync",
    preview:
      "Recapping what we landed on this morning. Three owners assigned — let me know if anything looks off.",
    timeLabel: "Sat",
    unread: false,
    hasAttachment: false,
    starred: true,
  },
  {
    id: "m-011",
    sender: "Kim Soo",
    senderInitial: "K",
    senderColor: "bg-lime-600",
    subject: "Holiday schedule",
    preview:
      "Sharing the proposed holiday rotation for June through August. Please mark your preferences by Thursday.",
    timeLabel: "5/22",
    unread: false,
    hasAttachment: false,
    starred: false,
  },
  {
    id: "m-012",
    sender: "Leo Park",
    senderInitial: "L",
    senderColor: "bg-fuchsia-500",
    subject: "System maintenance window",
    preview:
      "Heads up: scheduling a 30-minute maintenance window on 5/26 at 02:00 KST. No customer impact expected.",
    timeLabel: "5/20",
    unread: false,
    hasAttachment: false,
    starred: false,
  },
];

export const data = {
  all: () => seed.map((m) => ({ ...m })),
};
