/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as PinterestRouteImport } from './routes/pinterest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as PinterestIndexRouteImport } from './routes/pinterest.index'
import { Route as ProfilePostIdRouteImport } from './routes/profile.$postId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as PinterestPinIdRouteImport } from './routes/pinterest.$pinId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const PinterestRoute = PinterestRouteImport.update({
  id: '/pinterest',
  path: '/pinterest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const PinterestIndexRoute = PinterestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PinterestRoute,
} as any)
const ProfilePostIdRoute = ProfilePostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => ProfileRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const PinterestPinIdRoute = PinterestPinIdRouteImport.update({
  id: '/$pinId',
  path: '/$pinId',
  getParentRoute: () => PinterestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pinterest': typeof PinterestRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/pinterest/$pinId': typeof PinterestPinIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/profile/$postId': typeof ProfilePostIdRoute
  '/pinterest/': typeof PinterestIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pinterest/$pinId': typeof PinterestPinIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/profile/$postId': typeof ProfilePostIdRoute
  '/pinterest': typeof PinterestIndexRoute
  '/posts': typeof PostsIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pinterest': typeof PinterestRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/pinterest/$pinId': typeof PinterestPinIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/profile/$postId': typeof ProfilePostIdRoute
  '/pinterest/': typeof PinterestIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pinterest'
    | '/posts'
    | '/profile'
    | '/pinterest/$pinId'
    | '/posts/$postId'
    | '/profile/$postId'
    | '/pinterest/'
    | '/posts/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pinterest/$pinId'
    | '/posts/$postId'
    | '/profile/$postId'
    | '/pinterest'
    | '/posts'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/pinterest'
    | '/posts'
    | '/profile'
    | '/pinterest/$pinId'
    | '/posts/$postId'
    | '/profile/$postId'
    | '/pinterest/'
    | '/posts/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PinterestRoute: typeof PinterestRouteWithChildren
  PostsRoute: typeof PostsRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pinterest': {
      id: '/pinterest'
      path: '/pinterest'
      fullPath: '/pinterest'
      preLoaderRoute: typeof PinterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/pinterest/': {
      id: '/pinterest/'
      path: '/'
      fullPath: '/pinterest/'
      preLoaderRoute: typeof PinterestIndexRouteImport
      parentRoute: typeof PinterestRoute
    }
    '/profile/$postId': {
      id: '/profile/$postId'
      path: '/$postId'
      fullPath: '/profile/$postId'
      preLoaderRoute: typeof ProfilePostIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/pinterest/$pinId': {
      id: '/pinterest/$pinId'
      path: '/$pinId'
      fullPath: '/pinterest/$pinId'
      preLoaderRoute: typeof PinterestPinIdRouteImport
      parentRoute: typeof PinterestRoute
    }
  }
}

interface PinterestRouteChildren {
  PinterestPinIdRoute: typeof PinterestPinIdRoute
  PinterestIndexRoute: typeof PinterestIndexRoute
}

const PinterestRouteChildren: PinterestRouteChildren = {
  PinterestPinIdRoute: PinterestPinIdRoute,
  PinterestIndexRoute: PinterestIndexRoute,
}

const PinterestRouteWithChildren = PinterestRoute._addFileChildren(
  PinterestRouteChildren,
)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface ProfileRouteChildren {
  ProfilePostIdRoute: typeof ProfilePostIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfilePostIdRoute: ProfilePostIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PinterestRoute: PinterestRouteWithChildren,
  PostsRoute: PostsRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
