/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as PinterestRouteImport } from './routes/pinterest'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as PinterestIndexRouteImport } from './routes/pinterest.index'
import { Route as ProfilePostIdRouteImport } from './routes/profile.$postId'
import { Route as ProductsHomeRouteImport } from './routes/products.home'
import { Route as ProductsFashionRouteImport } from './routes/products.fashion'
import { Route as ProductsElectronicsRouteImport } from './routes/products.electronics'
import { Route as ProductsBeautyRouteImport } from './routes/products.beauty'
import { Route as ProductsAllRouteImport } from './routes/products.all'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as PinterestPinIdRouteImport } from './routes/pinterest.$pinId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const PinterestRoute = PinterestRouteImport.update({
  id: '/pinterest',
  path: '/pinterest',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const PinterestIndexRoute = PinterestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PinterestRoute,
} as any)
const ProfilePostIdRoute = ProfilePostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => ProfileRoute,
} as any)
const ProductsHomeRoute = ProductsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsFashionRoute = ProductsFashionRouteImport.update({
  id: '/fashion',
  path: '/fashion',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsElectronicsRoute = ProductsElectronicsRouteImport.update({
  id: '/electronics',
  path: '/electronics',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsBeautyRoute = ProductsBeautyRouteImport.update({
  id: '/beauty',
  path: '/beauty',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsAllRoute = ProductsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => ProductsRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const PinterestPinIdRoute = PinterestPinIdRouteImport.update({
  id: '/$pinId',
  path: '/$pinId',
  getParentRoute: () => PinterestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pinterest': typeof PinterestRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/pinterest/$pinId': typeof PinterestPinIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/products/all': typeof ProductsAllRoute
  '/products/beauty': typeof ProductsBeautyRoute
  '/products/electronics': typeof ProductsElectronicsRoute
  '/products/fashion': typeof ProductsFashionRoute
  '/products/home': typeof ProductsHomeRoute
  '/profile/$postId': typeof ProfilePostIdRoute
  '/pinterest/': typeof PinterestIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pinterest/$pinId': typeof PinterestPinIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/products/all': typeof ProductsAllRoute
  '/products/beauty': typeof ProductsBeautyRoute
  '/products/electronics': typeof ProductsElectronicsRoute
  '/products/fashion': typeof ProductsFashionRoute
  '/products/home': typeof ProductsHomeRoute
  '/profile/$postId': typeof ProfilePostIdRoute
  '/pinterest': typeof PinterestIndexRoute
  '/posts': typeof PostsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pinterest': typeof PinterestRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/pinterest/$pinId': typeof PinterestPinIdRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/products/all': typeof ProductsAllRoute
  '/products/beauty': typeof ProductsBeautyRoute
  '/products/electronics': typeof ProductsElectronicsRoute
  '/products/fashion': typeof ProductsFashionRoute
  '/products/home': typeof ProductsHomeRoute
  '/profile/$postId': typeof ProfilePostIdRoute
  '/pinterest/': typeof PinterestIndexRoute
  '/posts/': typeof PostsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pinterest'
    | '/posts'
    | '/products'
    | '/profile'
    | '/pinterest/$pinId'
    | '/posts/$postId'
    | '/products/all'
    | '/products/beauty'
    | '/products/electronics'
    | '/products/fashion'
    | '/products/home'
    | '/profile/$postId'
    | '/pinterest/'
    | '/posts/'
    | '/products/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pinterest/$pinId'
    | '/posts/$postId'
    | '/products/all'
    | '/products/beauty'
    | '/products/electronics'
    | '/products/fashion'
    | '/products/home'
    | '/profile/$postId'
    | '/pinterest'
    | '/posts'
    | '/products'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/pinterest'
    | '/posts'
    | '/products'
    | '/profile'
    | '/pinterest/$pinId'
    | '/posts/$postId'
    | '/products/all'
    | '/products/beauty'
    | '/products/electronics'
    | '/products/fashion'
    | '/products/home'
    | '/profile/$postId'
    | '/pinterest/'
    | '/posts/'
    | '/products/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PinterestRoute: typeof PinterestRouteWithChildren
  PostsRoute: typeof PostsRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pinterest': {
      id: '/pinterest'
      path: '/pinterest'
      fullPath: '/pinterest'
      preLoaderRoute: typeof PinterestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/pinterest/': {
      id: '/pinterest/'
      path: '/'
      fullPath: '/pinterest/'
      preLoaderRoute: typeof PinterestIndexRouteImport
      parentRoute: typeof PinterestRoute
    }
    '/profile/$postId': {
      id: '/profile/$postId'
      path: '/$postId'
      fullPath: '/profile/$postId'
      preLoaderRoute: typeof ProfilePostIdRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/products/home': {
      id: '/products/home'
      path: '/home'
      fullPath: '/products/home'
      preLoaderRoute: typeof ProductsHomeRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/fashion': {
      id: '/products/fashion'
      path: '/fashion'
      fullPath: '/products/fashion'
      preLoaderRoute: typeof ProductsFashionRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/electronics': {
      id: '/products/electronics'
      path: '/electronics'
      fullPath: '/products/electronics'
      preLoaderRoute: typeof ProductsElectronicsRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/beauty': {
      id: '/products/beauty'
      path: '/beauty'
      fullPath: '/products/beauty'
      preLoaderRoute: typeof ProductsBeautyRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/all': {
      id: '/products/all'
      path: '/all'
      fullPath: '/products/all'
      preLoaderRoute: typeof ProductsAllRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/pinterest/$pinId': {
      id: '/pinterest/$pinId'
      path: '/$pinId'
      fullPath: '/pinterest/$pinId'
      preLoaderRoute: typeof PinterestPinIdRouteImport
      parentRoute: typeof PinterestRoute
    }
  }
}

interface PinterestRouteChildren {
  PinterestPinIdRoute: typeof PinterestPinIdRoute
  PinterestIndexRoute: typeof PinterestIndexRoute
}

const PinterestRouteChildren: PinterestRouteChildren = {
  PinterestPinIdRoute: PinterestPinIdRoute,
  PinterestIndexRoute: PinterestIndexRoute,
}

const PinterestRouteWithChildren = PinterestRoute._addFileChildren(
  PinterestRouteChildren,
)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface ProductsRouteChildren {
  ProductsAllRoute: typeof ProductsAllRoute
  ProductsBeautyRoute: typeof ProductsBeautyRoute
  ProductsElectronicsRoute: typeof ProductsElectronicsRoute
  ProductsFashionRoute: typeof ProductsFashionRoute
  ProductsHomeRoute: typeof ProductsHomeRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsAllRoute: ProductsAllRoute,
  ProductsBeautyRoute: ProductsBeautyRoute,
  ProductsElectronicsRoute: ProductsElectronicsRoute,
  ProductsFashionRoute: ProductsFashionRoute,
  ProductsHomeRoute: ProductsHomeRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ProfileRouteChildren {
  ProfilePostIdRoute: typeof ProfilePostIdRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfilePostIdRoute: ProfilePostIdRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PinterestRoute: PinterestRouteWithChildren,
  PostsRoute: PostsRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
